### ISSUE TITLE
Compare GSWP3 to newer ERA5-W5E5

### ISSUE THREAD

**Issue by matthiasmengel** [ISI-MIP/attrici#69]
We have not decided, which dataset to put out first for attributions runs. Should be decided based on our analysis. So we should run W5E5 as well and see which one we trust more.

**Comment by matthiasmengel** [comment]
As discussed with Katja. One important test would to compare the trends in the non-counterfactuals datasets. Over the same time period, like 1900-2010, are the trends similar or very different. If very different, that would mean trends are induced by the concatenation of the two datasets, which would then produce spurious trends in the counterfactuals.

**Comment by matthiasmengel** [comment]
@SimonTreu

**Comment by SimonTreu** [comment]
so if trends are similar, take ERA5-W5E5
if trends differ, take GSWP3
?

**Comment by matthiasmengel** [comment]
Pseudocode, ha! Yes, I would think as you suggest. There may be other measures as well that influence our decision.

**Comment by matthiasmengel** [comment]
This is largely done. Close here.
