### ISSUE TITLE
Most extreme events are often not adjusted

### ISSUE THREAD

**Issue by matthiasmengel** [ISI-MIP/attrici#73]
For example for precipiation at `lat = 69.75, lon = -139.75` there is one extreme rainfall event around the year 1920. This event fails to be estimated in quantile mapping as `scipy.stats.distribution` most probably cannot map it. As we map `inf` and `nan` values from quantile mapping to the original values, this event stays unadjusted.

This is a problem as the most extreme events are of key interest, and just leaving them as they are takes them out for attribution assessments. 
![image](https://user-images.githubusercontent.com/1313086/73179866-81241b80-4114-11ea-92d5-6e0478a415f4.png)

**Comment by SimonTreu** [comment]
The Gamma-distribution might not be optimal to model high precipitation amounts. Some approaches use a different distribution for precipitation amounts that exceed a certain threshold.
