### ISSUE TITLE
Inf values in precip counterfactual

### ISSUE THREAD

**Issue by matthiasmengel** [ISI-MIP/attrici#78]
There are remaining inf values for precipitation. Quick fix would be: use original values where counterfactual is inf.

**Comment by matthiasmengel** [comment]
This has been fixed in the latest version, right @SimonTreu ? Can you close then?

**Comment by SimonTreu** [comment]
Hm didn't you say there were still some inf or nan values in the GSWP3-W5E5 dataset? If so, than it is still not fixed in the code but only in post-processing
