### ISSUE TITLE
Documentation under WSL

### ISSUE THREAD

**Issue by AnnaBooki** [ISI-MIP/attrici#85]
Under windows with WSL i could create the counterfactual data for precipitation and temperature. 
I wrote some notes mostly regarding package installation (incompatibilities of theano and pymc3) for WSL and adapted some code lines in the scripts when using the test datasets: 

##### Modified scripts:
```
run_estimation.py
tas_example.pynb
``` 
Should i create a new branch with an adapted README and adapted scripts to include the notes or just post my notes as an issue?

**Comment by SimonTreu** [comment]
Cool, I think a new branch would be good.

**Comment by AnnaBooki** [comment]
Great, i will add the new branch the next days and would close the issue.

**Comment by AnnaBooki** [comment]
Could you maybe provide me with the permission to add a new branch to the repo?

**Comment by SimonTreu** [comment]
> 

@matthiasmengel

**Comment by matthiasmengel** [comment]
Hope this works now.

**Comment by AnnaBooki** [comment]
Yes, great. Thanks!
