### ISSUE TITLE
Does an Update to the latest pymc give us speed improvements?

### ISSUE THREAD

**Issue by SimonTreu** [ISI-MIP/attrici#89]
@AnnaBooki could you please compare the run-times of pymc3 and latest pymc

1. Install a second conda environment for the latest pymc version. You may find the environment.yml in the [update_pymc branch](https://github.com/ISI-MIP/attrici/tree/update_pymc/config)
2. Activate the environment and run `pip install -p .` in the project base
3. Copy the folder `/p/tmp/sitreu/projects/attrici/runscripts/attrici_era5_02` somewhere where you have write access. (rename it appropriately)
4. Change settings.py (add `elif user == "..."` with the same settings as in the block following `elif user == "sitreu":`)
5. Update slurm.sh -> change log locations, tmpdir, compiledir and conda/env path
6. Make two versions of this folder (with same content) named e.g.  attrici_era5_pymc3 and attrici_era5_pymc5
7. Copy run_estimator.py from the [update_pymc branch](https://github.com/ISI-MIP/attrici/tree/era5_europe) into the `attrici_era5_pymc3` folder and  `run_estimator.py` from the [update_pymc branch](https://github.com/ISI-MIP/attrici/tree/update_pymc) into the `attrici_era5_pymc5` folder
8.a checkout the [update_pymc branch](https://github.com/ISI-MIP/attrici/tree/update_pymc) and run `attrici_era5_pymc5/slurm.sh` with the new conda environment for the latest pymc version.
8.b checkout the [era5_europe branch](https://github.com/ISI-MIP/attrici/tree/era5_europe) and run `attrici_era5_pymc5/slurm.sh` with the old conda environment with pymc3

We can then compare the runtimes in the logs.

**Comment by AnnaBooki** [comment]
Hi Simon,

thanks for the nice documentation.
Most of the packages in the environment.yml in the [update_pymc branch](https://github.com/ISI-MIP/attrici/tree/update_pymc/config) couldn't be installed right away in a new conda env on the HPC-cluster - due that they weren't found in the channel. Without spending to much time looking for the reason, i simply followed the installation instruction from the [pymc website](https://www.pymc.io/projects/docs/en/stable/installation.html) : 
"""
conda create -c conda-forge -n attrici_pymc5 "pymc>=5" python=3.10.11
"""
Followed by the installation instructions from the [master branch](https://github.com/ISI-MIP/attrici/tree/master) for the remaining packages.
I couldnt install higher versions of pymc such as pymc=5.3.0 or the most recent version pymc=5.5.0 for python 3.10.11 in a new conda env on the HPC-cluster (version on the HPC is pymc=5.0.0). 

If it's fine would pass my documentation for the installation the HPC to a README file in an existing branch or a new branch.

**Comment by AnnaBooki** [comment]
Regarding pymc3:
_8.b checkout the [era5_europe branch](https://github.com/ISI-MIP/attrici/tree/era5_europe) and run attrici_era5_pymc5/slurm.sh with the old conda environment with pymc_
It seems that there is a problem with theano and pymc3 in models.py line 138
	- ERROR (theano.gof.cmodule): [Errno 2] No such file or directory: 'g++': 'g++'
I couldnt find a solution right now to solve this
what i've checked: 
- is the theanorc file
- tested the same run_estimation.py with the develop branch in the old conda env -  which seems to work fine
[failing_cells.log](https://github.com/ISI-MIP/attrici/files/11898447/failing_cells.log)
 branch)

**Comment by SimonTreu** [comment]
> Regarding pymc3: _8.b checkout the [era5_europe branch](https://github.com/ISI-MIP/attrici/tree/era5_europe) and run attrici_era5_pymc5/slurm.sh with the old conda environment with pymc_ It seems for me that there is a problem with theano and pymc3 in models.py line 138 - ERROR (theano.gof.cmodule): [Errno 2] No such file or directory: 'g++': 'g++' I couldnt find a solution right now to solve this, what i've checked so far:
> 
> * is the theanorc file - it's identical to other thenaorc files (likewise the one from [era5_europe branch](https://github.com/ISI-MIP/attrici/tree/era5_europe) )
> * replaced only the models.py with the models.py from [master branch](https://github.com/ISI-MIP/attrici/tree/master) - which resulted in the same error
>   [failing_cells.log](https://github.com/ISI-MIP/attrici/files/11898447/failing_cells.log)

I will have a look now. I think it can be solved by loading the correct libraries with module load in `slurm.sh`

**Comment by SimonTreu** [comment]
@AnnaBooki can you uncomment some of the `module` commands in the `slurm.sh` script to get the following:

    module purge
    module load compiler/gnu/7.3.0
    module load anaconda/2021.11
    module load git

**Comment by AnnaBooki** [comment]
Great, this solved it! 
The results are located in : /p/tmp/annabu/log/

**Comment by SimonTreu** [comment]
Looks like there is a substantial speed improvement with the update. See below a comparison between two cleaned log files. for job 211. find_map arrived at the same log-probability and the same gradient but took 5 seconds for pymc5 and 46 seconds for pymc3. The speed improvement was not always that much but it was always sufficient. I will still check if the counterfactuals are identical for both versions.

![image](https://github.com/ISI-MIP/attrici/assets/9370249/283b7a42-7c71-460c-9a12-25d07d76a3d5)

**Comment by SimonTreu** [comment]
We should be able to improve the IO time by rechunking the inputs. I am working on a script for that at the moment.

**Comment by SimonTreu** [comment]
results are equal. Tested for one example cell with

    example_cell_pymc3 = pd.read_hdf("/p/tmp/annabu/attrici_era5_02_pymc3/attrici_output/timeseries/tas/lat_52.24166666666666/ts_ERA5_lat52.24166666666666_lon-10.158333333333335.h5")

    example_cell_pymc5 = pd.read_hdf("/p/tmp/annabu/attrici_era5_02_pymc5/attrici_output/timeseries/tas/lat_52.24166666666666/ts_ERA5_lat52.24166666666666_lon-10.158333333333335.h5")

    pd.testing.assert_frame_equal(example_cell_pymc3, example_cell_pymc5)

**Comment by SimonTreu** [comment]
> Hi Simon,
> 
> thanks for the nice documentation. Most of the packages in the environment.yml in the [update_pymc branch](https://github.com/ISI-MIP/attrici/tree/update_pymc/config) couldn't be installed right away in a new conda env on the HPC-cluster - due that they weren't found in the channels. Without spending to much time looking for the reason, i simply followed the installation instruction from the [pymc website](https://www.pymc.io/projects/docs/en/stable/installation.html) : `conda create -c conda-forge -n attrici_pymc5 "pymc>=5" python=3.10.11` Followed by the installation instructions from the [master branch](https://github.com/ISI-MIP/attrici/tree/master) for the remaining packages. I couldnt install higher versions of pymc such as pymc=5.3.0 or the most recent version pymc=5.5.0 for python 3.10.11 in a new conda env on the HPC-cluster (version on the HPC is pymc=5.0.0).
> 
> If it's fine would pass my documentation for the installation the HPC to a README file in an existing branch or a new branch.

Please add your documentation to the README.md in the [update_pymc branch](https://github.com/ISI-MIP/attrici/tree/update_pymc)

Afterwards this issue can be closed
