### ISSUE TITLE
Update code to pymc5 for all variables in models.py

### ISSUE THREAD

**Issue by SimonTreu** [ISI-MIP/attrici#90]
Please apply the changes 40c3fa3dccc78ab95c69ce7043d6f9c4f64e3c54 that were done for the class `Tas` in `models.py` to all other classes. Similarly for the respective distributions (BernoulliGamma, Beta, Gamma and Weibull) in `distribution.py`. Note that the class `RsdsWeibull` is not used and can be ignored.

Please make (at least) one commit per variable in `models.py` and start with variables using the `Normal` distribution. 

Test your changes on the ERA5 file for the respective variable. It is enough to do run only until one cell is computed without breaking. E.g. you can use `bash slurm.sh` instead of `sbatch slurm.sh` on the cluster to run the code in the shell on the login node.

If this does not go straight forward please come back to me.

**Comment by AnnaBooki** [comment]
For class `sfcwind`  it comes from the `estimator.py` and `const.py`:

Traceback (most recent call last):
  File "/p/tmp/annabu/attrici_era5_02_pymc5/run_estimation.py", line 92, in <module>
    estimator = est.estimator(s)
  File "/p/tmp/annabu/attrici_era5_02_pymc5/attrici/estimator.py", line 41, in __init__
    self.f_rescale = c.mask_and_scale[cfg.variable][1]
KeyError: 'sfcWind'

I will have a look on it later today again.

**Comment by SimonTreu** [comment]
> For class `sfcwind` it comes from the `estimator.py` and `const.py`: I have pushed both errors to the update_pymc branch and would have a look on both errors again later today.
> 
> ```
> Traceback (most recent call last):
>   File "/p/tmp/annabu/attrici_era5_02_pymc5/run_estimation.py", line 92, in <module>
>     estimator = est.estimator(s)
>   File "/p/tmp/annabu/attrici_era5_02_pymc5/attrici/estimator.py", line 41, in __init__
>     self.f_rescale = c.mask_and_scale[cfg.variable][1]
> KeyError: 'sfcWind'
> ```

just copy line 137: `"sfcwind": [scale_and_mask, refill_and_rescale]
`
and change `sfcwind` to `sfcWind`

**Comment by AnnaBooki** [comment]
Hi,

the timeseries data is finally created for all meteorological classes, including Pr. 
The files are stored in : `/p/tmp/annabu/projects/attrici/runscripts/attrici_era5_02_pymc5/attrici_output/`
